name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-summary-cards

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: thaiza-d
          BRANCH_NAME: "main"
          UTC_OFFSET: -3
          AUTO_PUSH: false

      - name: Commit and push cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile-summary-card-output/

          if git diff --cached --quiet; then
            echo "Nenhuma alteração nos gráficos."
          else
            git commit -m "chore: update profile summary cards"
            git push origin main
          fi
